[package]
name = "chamber_cst"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chamber_text_size = { path = "../chamber_text_size" }
chamber_syntax = { path = "../chamber_syntax" }
